### ISSUE TITLE
SARS-CoV-2 Variants

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/covid-19-wastewater#98] opened 2021-02-12 20:19 UTC
Currently, there is no way of reporting on variants of the virus. Should this be included?

**Comment by DougManuel** [comment] 2021-02-15 19:23
Yes. Ottawa is starting to report presence of B.1.1.7. In the future, Ottawa will likely report the proportion of different variants.

This is a duplicate of #59.

**Closed by DougManuel** 2021-02-15 19:23 UTC
Labels: question
